import "./globals.scss";
import type { Metadata } from "next";
import ThemeRegistry from "./ThemeRegistry";
import { Open_Sans } from "next/font/google";

const font = Open_Sans({
  weight: ["300", "400", "500", "700"],
  subsets: ["cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Моя історія",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk" className={font.className}>
      <body>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
